workdir: config["workdir"]


# shell settings
shell.executable("/bin/bash")
shell.prefix("set +eu; ")


rule all:
    input:
        "qc/multiqc.html",
        expand("qc/RPKM_saturation/{sample}.saturation.pdf", sample=config["samples"]),
        expand("qc/qualimap_rnaseq/{sample}", sample=config["samples"]),
        "trimmed/fastp.stats.tsv",
        "feature_counts/gene_count.tsv",


include: "rules/common.smk"
include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/hisat2_align.smk"
include: "rules/qualimap_rnaseq.smk"
include: "rules/feature_counts.smk"
include: "rules/rseqc_saturation.smk"
