$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  conda:
    type: object
    properties:
      R:
        type: string
      python:
        type: string
      Rpheatmap:
        type: string
      fastp:
        type: string
      fastqc:
        type: string
      featurecounts:
        type: string
      hisat2:
        type: string
      multiqc:
        type: string
      qualimap:
        type: string
      rseqc:
        type: string

  database:
    type: object
    properties:
      hisat2_index:
        type: string
      gtf:
        type: string
      rseqc_bed:
        type: string

  metadata:
    type: string

  samples:
    type: array
    items:
      type: string

  threads:
    type: object
    properties:
      high:
        type: integer
      low:
        type: integer
      max:
        type: integer
    required:
      - high
      - low
      - max

  workdir:
    type: string

required:
  - conda
  - samples
  - threads
  - workdir
