$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  conda:
    type: object
    properties:
      R:
        type: string
      basic:
        type: string
      rnaseq:
        type: string
      python:
        type: string
    required:
      - R
      - basic
      - rnaseq
      - python

  database:
    type: object
    properties:
      hisat2_index:
        type: string
      gtf:
        type: string

  metadata:
    type: string

  samples:
    type: array
    items:
      type: string

  threads:
    type: object
    properties:
      high:
        type: integer
      low:
        type: integer
      max:
        type: integer
    required:
      - high
      - low
      - max

  workdir:
    type: string

required:
  - conda
  - samples
  - threads
  - workdir
